// Auto-generated by VIP Connect Bot — do not edit manually
// To update, post changes in the event's Slack channel

export const eventConfig = {
  "city": "Cannes",
  "venue": "Moloco penthouse in Cannes, France",
  "capacity": 15,
  "eventTitle": "VIP Connect — Cannes Leadership Dinner",
  "heroImageUrl": "/venue/long-table.png",
  "heroHeadline": "VIP Connect",
  "heroSubheadline": "Cannes Leadership Dinner",
  "heroDescription": "An invitation-only gathering for senior leaders shaping the future of commerce and machine learning.",
  "experienceHeadline": "15 leaders.\nNo slides.",
  "experienceParagraphs": [
    "A closed-door, invitation-only evening designed for connection, not networking. The group is deliberately small. Senior enough to speak candidly, diverse enough to challenge each other's assumptions.",
    "The conversation centres on what machine learning is actually changing in commerce. Not the theory, but the reality. What's working, what's not, and what the next twelve months look like.",
    "Join us at the Moloco penthouse for an evening of exceptional dining and strategic dialogue high above the Mediterranean."
  ],
  "agendaItems": [
    {
      "time": "7:00 PM",
      "title": "Arrival & Welcome Drinks",
      "description": "Cocktails in the bar area. Introductions happen naturally when the setting is right and the group is deliberately small."
    },
    {
      "time": "7:30 PM",
      "title": "Executive Session",
      "description": "An unscripted discussion on the future of AI-driven performance, industry evolution, ecosystem collaboration, and what the next twelve months look like."
    },
    {
      "time": "7:45 PM",
      "title": "Dinner",
      "description": "An intimate evening exploring the future of AI in marketing with the industry's leading voices."
    },
    {
      "time": "10:00 PM",
      "title": "Event Close",
      "description": "An informal close as the evening winds down."
    }
  ],
  "agendaShort": [
    {
      "time": "7:00 PM",
      "label": "Arrival & welcome drinks"
    },
    {
      "time": "7:30 PM",
      "label": "Executive session"
    },
    {
      "time": "7:45 PM",
      "label": "Dinner"
    },
    {
      "time": "10:00 PM",
      "label": "Event close"
    }
  ],
  "faqItems": [
    {
      "q": "What is Moloco VIP Connect?",
      "a": "An invitation-only, in-person dinner designed for senior leaders across the commerce ecosystem, combining product innovation, industry insight, and high-quality peer discussion."
    },
    {
      "q": "Who is this event for?",
      "a": "Senior executives and leadership in growth, UA, product, monetisation, and performance marketing. We keep the group to around 15 people. Small enough that everyone speaks, diverse enough that you'll hear something that changes how you think about a problem."
    },
    {
      "q": "Is this a public event / can I bring a +1?",
      "a": "No. Attendance is by invitation only. Invitations may be shared with a relevant colleague or peer, subject to availability. Please check with us first before you share the RSVP link."
    },
    {
      "q": "What should I wear?",
      "a": "Smart casual. Polished but comfortable. Think what you'd wear to dinner with people you want to impress without looking like you tried."
    },
    {
      "q": "Is there a cost to attend?",
      "a": "No. The evening is complimentary for confirmed guests. Dinner, drinks, and the full programme are on Moloco."
    },
    {
      "q": "What about dietary requirements?",
      "a": "Moloco penthouse in Cannes, France accommodates dietary needs: vegetarian, vegan, gluten-free, allergies. Note yours on the registration form and they'll take care of it."
    }
  ],
  "calendarTitle": "Moloco VIP Connect — Cannes Leadership Dinner",
  "calendarUidPrefix": "moloco-vip-connect-2026",
  "siteUrl": "https://moloco-event-cannes-2.vercel.app",
  "slug": "moloco-event-cannes-2",
  "eventSubtitle": "An exclusive executive gathering in partnership with AdWeek",
  "venueAddress": "Moloco Penthouse, Cannes 06400",
  "venueAddressFull": "Moloco Penthouse, Cannes 06400, France",
  "date": "June 22, 2026",
  "dateFull": "Sunday, June 22",
  "dateISO": "2026-06-22",
  "calendarDateStart": "20260622T190000",
  "calendarDateEnd": "20260622T220000",
  "time": "7:00 PM",
  "timezone": "Europe/Paris",
  "timezoneAbbr": "CEST",
  "venueDescription": "Our exclusive penthouse sits high above the Mediterranean, offering sweeping views of the Côte d'Azur and the iconic Palais des Festivals. The sophisticated space features floor-to-ceiling windows, contemporary design elements, and private terraces that capture the golden hour light. This intimate setting provides the perfect backdrop for meaningful conversations while the French Riviera unfolds below.",
  "venueCapacityNote": "Our penthouse accommodates exactly 15 executives in an intimate setting designed for meaningful connections.",
  "venueDiningNote": "We'll serve a curated Mediterranean menu featuring the finest local ingredients and French Riviera flavors.",
  "venueDirections": "The penthouse is located in the heart of Cannes, within walking distance of the Palais des Festivals and La Croisette. Detailed access instructions will be provided upon RSVP confirmation. Valet parking can be arranged for those arriving by car.",
  "venueExperienceLine": "Join us at the Moloco penthouse for an evening of exceptional dining and strategic dialogue high above the Mediterranean.",
  "dinnerDescription": "An intimate evening exploring the future of AI in marketing with the industry's leading voices.",
  "mapsUrl": "https://maps.google.com/?q=Cannes,+France"
};